trigger:
- main

pr:
- main

jobs:
  # WIN32
  - template: .github/jobs/win32.yml
    parameters:
      name: Win32_x86
      vmImage: 'windows-latest'
      platform: win32

  - template: .github/jobs/win32.yml
    parameters:
      name: Win32_x64
      vmImage: 'windows-latest'
      platform: x64
