jobs:
- job: Android
  timeoutInMinutes: 15

  pool:
    vmImage: macos-latest

  steps:
  - task: Npm@1
    inputs:
      command: "install"
      workingDir: "Tests"
    displayName: 'Install NPM packages'

  - script: |
      echo sdkmanager --install
      echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-27;default;x86_64"
      echo sdkmanager --licenses
      echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --licenses
      echo avdmanager create avd
      $ANDROID_HOME/tools/bin/avdmanager create avd -n Pixel_API_27 -d pixel -k "system-images;android-27;default;x86_64"
    displayName: Install Android Emulator

  - script: |
      echo emulator -list-avds
      $ANDROID_HOME/emulator/emulator -list-avds
      echo nohup emulator -avd
      nohup $ANDROID_HOME/emulator/emulator -avd Pixel_API_27 -gpu host -no-audio -no-boot-anim -camera-back none -camera-front none -qemu -m 2048 2>&1 &
    displayName: Start Android Emulator

      # echo adb wait-for-device
      # $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do echo "wait..."; sleep 1; done; input keyevent 82'
      # echo adb devices
      # $ANDROID_HOME/platform-tools/adb devices

  - task: Gradle@3
    inputs:
      gradleWrapperFile: "Tests/UnitTests/Android/gradlew"
      workingDirectory: "Tests/UnitTests/Android"
      tasks: "connectedAndroidTest"
      jdkVersionOption: 1.11
    displayName: Run Connected Android Test

  - script: |
      adb logcat -s "JsRuntimeHost" -d
    displayName: Dump logcat
