parameters:
- name: name
  type: string
- name: jsEngine
  type: string

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 30

  pool:
    vmImage: macos-latest

  steps:
  - task: JavaToolInstaller@0
    displayName: 'Set up JDK 17'
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      echo "Install NDK and Android SDK"
      # Use Java 17 which is compatible with modern Android tooling
      export JAVA_HOME=$JAVA_HOME_17_X64
      export PATH=$JAVA_HOME/bin:$PATH
      # Clear any problematic Java options - not needed with Java 17
      unset _JAVA_OPTIONS

      echo "Java version:"
      java -version

      # Use cmdline-tools instead of deprecated tools/bin path
      echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;$(ndkVersion)"
      echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-35"
      echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;35.0.0"
      echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-35;google_apis;x86_64"
      echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      echo "Create AVD with Pixel 2 profile and optimized memory"
      echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n Pixel_2_API_35 -d pixel_2 -k "system-images;android-35;google_apis;x86_64"
      # Optimize AVD for CI - reduce memory and disk size
      echo "hw.ramSize=1024" >> ~/.android/avd/Pixel_2_API_35.avd/config.ini
      echo "disk.dataPartition.size=2G" >> ~/.android/avd/Pixel_2_API_35.avd/config.ini
      echo "hw.gpu.enabled=yes" >> ~/.android/avd/Pixel_2_API_35.avd/config.ini
      echo "hw.gpu.mode=swiftshader_indirect" >> ~/.android/avd/Pixel_2_API_35.avd/config.ini
    displayName: 'Install Android Emulator'

  - script: |
      export JAVA_HOME=$JAVA_HOME_17_X64
      export PATH=$JAVA_HOME/bin:$PATH
      unset _JAVA_OPTIONS

      echo Start emulator with optimized settings
      nohup $ANDROID_HOME/emulator/emulator -avd Pixel_2_API_35 -gpu swiftshader_indirect -no-window -no-audio -no-boot-anim -no-snapshot-save -memory 1024 -partition-size 2048 2>&1 &
      echo Wait for emulator
      $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do echo "Waiting for boot..."; sleep 2; done'
      $ANDROID_HOME/platform-tools/adb devices
    displayName: 'Start Android Emulator'

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'Tests/UnitTests/Android/gradlew'
      workingDirectory: 'Tests/UnitTests/Android'
      options: '-PabiFilters=x86_64 -PjsEngine=${{parameters.jsEngine}} -PndkVersion=$(ndkVersion)'
      tasks: 'connectedAndroidTest'
      jdkVersionOption: '1.17'
    displayName: 'Run Connected Android Test'

  - script: |
      find ./app/build/outputs/androidTest-results -name "*.txt" -print0 | while IFS= read -r -d '' file; do
        echo "cat \"$file\""
        cat "$file"
      done
    workingDirectory: 'Tests/UnitTests/Android'
    condition: succeededOrFailed()
    displayName: 'Dump logcat from Test Results'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'Tests/UnitTests/Android/app/build/outputs/androidTest-results/connected'
      artifactName: 'AndroidTestResults_${{parameters.jsEngine}}'
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'
