parameters:
- name: name
  type: string
- name: vmImage
  type: string

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 5

  pool:
    vmImage: ${{parameters.vmImage}}

  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'Tests'
    displayName: 'Install NPM packages'

  - task: Gradle@3
    inputs:
        gradleWrapperFile: 'Tests/UnitTests/Android/gradlew'
        workingDirectory: 'Tests/UnitTests/Android'
        tasks: 'assembleDebug'
        jdkVersionOption: 1.11
    displayName: 'Build UnitTests'
