parameters:
  name: ''
  vmImage: ''
  xCodeVersion: ''
  simulator: ''

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: ${{parameters.vmImage}}

  steps:
  - script: |
      sudo xcode-select --switch /Applications/Xcode_${{parameters.xCodeVersion}}.app/Contents/Developer
    displayName: 'Select XCode ${{parameters.xCodeVersion}}'

  - script: |
      cmake -B Build/iOS -G Xcode -D IOS=ON
    displayName: 'Configure CMake'

  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'Build/iOS/JsRuntimeHost.xcodeproj'
      scheme: 'UnitTests'
      sdk: 'iphonesimulator'
      useXcpretty: false
      configuration: RelWithDebInfo
    displayName: 'Build Xcode Project'

  - script: |
      echo Boot "${{parameters.simulator}}"
      xcrun simctl boot "${{parameters.simulator}}"
      echo Install UnitTests app
      xcrun simctl install booted "Build/iOS/Tests/UnitTests/RelWithDebInfo-iphonesimulator/UnitTests.app"
      echo Launch UnitTests app
      xcrun simctl launch --console booted "com.jsruntimehost.unittests" 2> /tmp/exitCode
      (exit $(cat /tmp/exitCode))
    displayName: 'Run Tests'
