jobs:
- job: iOS
  timeoutInMinutes: 15

  pool:
    vmImage: macos-latest

  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'Tests'
    displayName: 'Install NPM packages'

  - script: |
      sudo xcode-select --switch /Applications/Xcode_14.0.app/Contents/Developer
    displayName: 'Select XCode 14.0'

  - script: |
      cmake -B Build/iOS -G Xcode -D IOS=ON
    displayName: 'Configure CMake'

  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'Build/iOS/JsRuntimeHost.xcodeproj'
      scheme: 'UnitTests'
      sdk: 'iphoneos'
      useXcpretty: false
      configuration: Debug
    displayName: 'Build Xcode Project'
