parameters:
- name: name
  type: string
- name: vmImage
  type: string
- name: xcodeVersion
  type: string

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: ${{parameters.vmImage}}

  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'Tests'
    displayName: 'Install NPM packages'

  - script: |
      sudo xcode-select --switch /Applications/Xcode_${{parameters.xCodeVersion}}.app/Contents/Developer
    displayName: 'Select XCode ${{parameters.xCodeVersion}}'

  - script: |
      cmake -B Build/iOS -G Xcode -D IOS=ON
    displayName: 'Configure CMake'

  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'Build/iOS/JsRuntimeHost.xcodeproj'
      scheme: 'UnitTests'
      sdk: 'iphoneos'
      useXcpretty: false
      configuration: Debug
    displayName: 'Build Xcode Project'
