parameters:
  name: ''
  enableSanitizers: false

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: ubuntu-latest

  variables:
    SANITIZER_FLAG: ${{ coalesce(replace(format('{0}', parameters.enableSanitizers), 'True', 'ON'), 'OFF') }}

  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install libjavascriptcoregtk-4.1-dev libcurl4-openssl-dev ninja-build
    displayName: 'Install packages'

  - script: cmake -B Build/ubuntu -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_SANITIZERS=$(SANITIZER_FLAG)
    displayName: 'Configure CMake'

  - script: |
      cd Build/ubuntu
      ninja
    displayName: 'Build Solution'

  - script: ./UnitTests
    workingDirectory: 'Build/ubuntu/Tests/UnitTests'
    displayName: 'Run Tests'
