jobs:
- job: ubuntu
  timeoutInMinutes: 15

  pool:
    vmImage: ubuntu-latest

  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install libjavascriptcoregtk-4.0-dev libcurl4-openssl-dev ninja-build
    displayName: 'Install packages'

  - script: cmake -B Build/ubuntu -GNinja -D CMAKE_BUILD_TYPE=RelWithDebInfo
    displayName: 'Configure CMake'

  - script: |
      cd Build/ubuntu
      ninja
    displayName: 'Build Solution'

  - script: ./UnitTests
    workingDirectory: 'Build/ubuntu/Tests/UnitTests'
    displayName: 'Run Tests'
