jobs:
- job: ubuntu
  timeoutInMinutes: 15

  pool:
    vmImage: ubuntu-latest

  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install libjavascriptcoregtk-4.0-dev libgl1-mesa-dev libcurl4-openssl-dev
    displayName: 'Install packages'

  - script: cmake -B Build/ubuntu
    displayName: 'Configure CMake'

  - script: |
      cmake -GNinja -DJSCORE_LIBRARY=/usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so -DNAPI_JAVASCRIPT_ENGINE=JavaScriptCore -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBGFX_CONFIG_DEBUG=ON
    displayName: 'Build Solution'

  - script: ./UnitTests
    workingDirectory: 'Build/ubuntu/Tests/UnitTests/RelWithDebInfo'
    displayName: 'Run Tests'
