parameters:
  name: ''
  enableSanitizers: false
  CC: gcc
  CXX: g++
  jsEngine: 'JavaScriptCore'

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: ubuntu-latest

  variables:
    SANITIZER_FLAG: ${{ coalesce(replace(format('{0}', parameters.enableSanitizers), 'True', 'ON'), 'OFF') }}

  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install libjavascriptcoregtk-4.1-dev libcurl4-openssl-dev ninja-build clang
    displayName: 'Install packages'

  - script: |
      export CC=${{parameters.CC}}
      export CXX=${{parameters.CXX}}
      cmake -B Build/ubuntu -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_SANITIZERS=$(SANITIZER_FLAG) -D CMAKE_C_COMPILER=${{parameters.CC}} -D CMAKE_CXX_COMPILER=${{parameters.CXX}} -D NAPI_JAVASCRIPT_ENGINE=${{parameters.jsEngine}}
    displayName: 'Configure CMake'

  - script: |
      cd Build/ubuntu
      ninja
    displayName: 'Build Solution'

  - script: ./UnitTests
    workingDirectory: 'Build/ubuntu/Tests/UnitTests'
    displayName: 'Run Tests'
