parameters:
  name: ''
  vmImage: ''
  xCodeVersion: ''
  enableSanitizers: false

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: ${{parameters.vmImage}}

  variables:
    SANITIZER_FLAG: ${{ coalesce(replace(format('{0}', parameters.enableSanitizers), 'True', 'ON'), 'OFF') }}

  steps:
  - script: |
      sudo xcode-select --switch /Applications/Xcode_${{parameters.xCodeVersion}}.app/Contents/Developer
    displayName: 'Select Xcode ${{parameters.xCodeVersion}}'

  - script: |
      cmake -B Build/macOS -G Xcode -D ENABLE_SANITIZERS=$(SANITIZER_FLAG)
    displayName: 'Configure CMake'

  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'Build/macOS/JsRuntimeHost.xcodeproj'
      scheme: 'UnitTests'
      sdk: 'macosx'
      useXcpretty: false
      configuration: RelWithDebInfo
    displayName: 'Build Xcode Project'

  - script: ./UnitTests
    workingDirectory: 'Build/macOS/Tests/UnitTests/RelWithDebInfo'
    displayName: 'Run Tests'
