jobs:
- job: macOS
  timeoutInMinutes: 15

  pool:
    vmImage: macos-latest

  steps:
  - script: |
      sudo xcode-select --switch /Applications/Xcode_14.0.app/Contents/Developer
    displayName: 'Select Xcode 14.0'

  - script: |
      cmake -B Build/macOS -GXcode
    displayName: 'Configure CMake'

  - task: Xcode@5
    inputs:
      xcWorkspacePath: 'Build/macOS/JsRuntimeHost.xcodeproj'
      scheme: 'UnitTests'
      sdk: 'macosx'
      useXcpretty: false
      configuration: RelWithDebInfo
    displayName: 'Build Xcode Project'

  - script: ./UnitTests
    workingDirectory: 'Build/macOS/Tests/UnitTests/RelWithDebInfo'
    displayName: 'Run Tests'
