parameters:
  name: ''
  vmImage: ''
  xCodeVersion: ''
  enableSanitizers: false
  jsEngine: 'JavaScriptCore'
  generator: 'Xcode'

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: ${{parameters.vmImage}}

  variables:
    SANITIZER_FLAG: ${{ coalesce(replace(format('{0}', parameters.enableSanitizers), 'True', 'ON'), 'OFF') }}

  steps:
  - script: |
      sudo xcode-select --switch /Applications/Xcode_${{parameters.xCodeVersion}}.app/Contents/Developer
    displayName: 'Select Xcode ${{parameters.xCodeVersion}}'

  - script: |
      cmake -B Build/macOS -G "${{parameters.generator}}" -D NAPI_JAVASCRIPT_ENGINE=${{parameters.jsEngine}} -D ENABLE_SANITIZERS=$(SANITIZER_FLAG) -D CMAKE_BUILD_TYPE=RelWithDebInfo
    displayName: 'Configure CMake'

  - ${{ if eq(parameters.generator, 'Xcode') }}:
    - task: Xcode@5
      inputs:
        xcWorkspacePath: 'Build/macOS/JsRuntimeHost.xcodeproj'
        scheme: 'UnitTests'
        sdk: 'macosx'
        useXcpretty: false
        configuration: RelWithDebInfo
      displayName: 'Build Xcode Project'

    - script: ./UnitTests
      workingDirectory: 'Build/macOS/Tests/UnitTests/RelWithDebInfo'
      displayName: 'Run Tests'

  - ${{ if ne(parameters.generator, 'Xcode') }}:
    - script: cmake --build Build/macOS --target UnitTests --config RelWithDebInfo -j
      displayName: 'Build'

    - script: ./UnitTests
      workingDirectory: 'Build/macOS/Tests/UnitTests'
      displayName: 'Run Tests'
