parameters:
- name: name
  type: string
- name: platform
  type: string
- name: jsEngine
  type: string

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: windows-latest

  steps:
  - script: cmake -B Build/UWP -A ${{parameters.platform}} -D NAPI_JAVASCRIPT_ENGINE=${{parameters.jsEngine}} -D CMAKE_SYSTEM_NAME=WindowsStore -D CMAKE_SYSTEM_VERSION=10.0 
    displayName: 'Configure CMake'

  - task: MSBuild@1
    inputs:
      solution: 'Build/UWP/JsRuntimeHost.sln'
      maximumCpuCount: true
      configuration: 'RelWithDebInfo'
    displayName: 'Build Solution'

