parameters:
- name: name
  type: string
- name: vmImage
  type: string
- name: platform
  type: string

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: ${{parameters.vmImage}}

  variables:
    solutionName: 'Win32_${{parameters.platform}}'
    buildDir: 'Build/${{variables.solutionName}}'

  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'Tests'
    displayName: 'Install NPM packages'

  - script: cmake -B ${{variables.buildDir}} -A ${{parameters.platform}}
    displayName: 'Configure CMake'

  - task: MSBuild@1
    inputs:
      solution: '${{variables.buildDir}}/JsRuntimeHost.sln'
      maximumCpuCount: true
      configuration: 'RelWithDebInfo'
    displayName: 'Build Solution'

  - script: UnitTests.exe
    workingDirectory: '${{variables.buildDir}}/Tests/UnitTests/RelWithDebInfo'
    displayName: 'Run Tests'
