parameters:
- name: name
  type: string
- name: platform
  type: string
- name: jsEngine
  type: string

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: windows-latest

  steps:
  - script: cmake -B Build/Win32 -A ${{parameters.platform}} -D NAPI_JAVASCRIPT_ENGINE=${{parameters.jsEngine}}
    displayName: 'Configure CMake'

  - task: MSBuild@1
    inputs:
      solution: 'Build/Win32/JsRuntimeHost.sln'
      maximumCpuCount: true
      configuration: 'Debug'
    displayName: 'Build Solution'

  - script: |
      reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\UnitTests.exe"
      reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\UnitTests.exe" /v DumpType /t REG_DWORD /d 2
      reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\UnitTests.exe" /v DumpCount /t REG_DWORD /d 1
      reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\UnitTests.exe" /v DumpFolder /t REG_SZ /d "$(Build.ArtifactStagingDirectory)/Dumps"
    displayName: 'Enable Crash Dumps'

  - task: CopyFiles@2
    inputs:
      sourceFolder: 'Build/Win32/Tests/UnitTests/Debug'
      contents: UnitTests.*
      targetFolder: '$(Build.ArtifactStagingDirectory)/Dumps'
      cleanTargetFolder: false
    displayName: 'Stage test app exe/pdb for publishing'
    condition: failed()

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'Crash Dumps'
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/Dumps'
    displayName: 'Publish Tests Dumps'
    condition: failed()

  - script: UnitTests.exe
    workingDirectory: 'Build/Win32/Tests/UnitTests/Debug'
    displayName: 'Run Tests'
