parameters:
- name: name
  type: string
- name: platform
  type: string

jobs:
- job: ${{parameters.name}}
  timeoutInMinutes: 15

  pool:
    vmImage: windows-latest

  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'Tests'
    displayName: 'Install NPM packages'

  - script: cmake -B Build/Win32 -A ${{parameters.platform}}
    displayName: 'Configure CMake'

  - task: MSBuild@1
    inputs:
      solution: 'Build/Win32/JsRuntimeHost.sln'
      maximumCpuCount: true
      configuration: 'Debug'
    displayName: 'Build Solution'

  - script: UnitTests.exe
    workingDirectory: 'Build/Win32/Tests/UnitTests/Debug'
    displayName: 'Run Tests'
